### ISSUE TITLE
Please provide a pretrained model of some sorts

### ISSUE THREAD

**Issue by ashupednekar** [oscarknagg/one-shot-speaker-identification#2]
It is not possible to download such a huge dataset for those with limited bandwidth. It would be great if there were a pre-trained model available.

**Comment by andrewMpapalika** [comment]
Hi @ashupednekar 

In my case I changed the cell above the "load_model(model_path)" cell to

model_path = '../models/n_seconds/siamese__nseconds_3.0__filters_32__embed_64__drop_0.05__r_0.hdf5'

and downloaded the model file from
https://github.com/oscarknagg/voicemap/tree/master/models/n_seconds

I save the downloaded file to "../models/n_seconds/" and I was able to run the model without a problem. If you haven't tried the above, please try it to see if it works for you.

Thanks,
Andrew

**Comment by celikmustafa89** [comment]
> Hi @ashupednekar
> 
> In my case I changed the cell above the "load_model(model_path)" cell to
> 
> model_path = '../models/n_seconds/siamese__nseconds_3.0__filters_32__embed_64__drop_0.05__r_0.hdf5'
> 
> and downloaded the model file from
> https://github.com/oscarknagg/voicemap/tree/master/models/n_seconds
> 
> I save the downloaded file to "../models/n_seconds/" and I was able to run the model without a problem. If you haven't tried the above, please try it to see if it works for you.
> 
> Thanks,
> Andrew

i did the same thing it is not working having following error "bad marshall" something

`Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 231, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mustafacelik/PycharmProjects/voicemap/mustafa.py", line 16, in <module>
    siamese = load_model(model_path)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 260, in load_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/saving.py", line 334, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.7/site-packages/keras/engine/network.py", line 1017, in from_config
    process_layer(layer_data)
  File "/usr/local/lib/python3.7/site-packages/keras/engine/network.py", line 1003, in process_layer
    custom_objects=custom_objects)
  File "/usr/local/lib/python3.7/site-packages/keras/layers/__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "/usr/local/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "/usr/local/lib/python3.7/site-packages/keras/layers/core.py", line 730, in from_config
    function = func_load(config['function'], globs=globs)
  File "/usr/local/lib/python3.7/site-packages/keras/utils/generic_utils.py", line 235, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)`
